---
title: "zotero_to_word"
output:
  word_document: default
---

Plan:
# 1. Import the bibtex and json file for the papers
```{r}
#for citing:
#possibly not needed after making the reference on our own
if (!requireNamespace("RefManageR", quietly = TRUE)) {
  install.packages("RefManageR") }
library(RefManageR)
bib_file <- ReadBib("LMUOpenScienceCenter_MembersPublications.bib")


# For filtering:
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite") }
library(jsonlite)
json_data <- read_json("LMUOpenScienceCenter_MembersPublications_Better.json")
items <- json_data$items
```

# 2. Filter For "Tags" "m_true" OR "g_true" #papers perceived as meeting the criteria that the raters m or g deemed fitting
```{r}
#Going through all the papers we will look at all tags and check if they are m_true or g_true
citation_keys <- c() # getting the citation IDs for in text use
i_true <- c() # getting a list of all the references 
i = 0
for (item in items) {
  tags <- item$tags
  i <- i + 1
  for (tag in tags) {
    #change open science to m_true once the rating is in no longer in testing phase
    if ("open science" == tag | "g_true" == tag) {
      # If it is, add the corresponding 'citationKey' to 'citation_keys'
      citation_keys <- c(citation_keys, item$citationKey)
      i_true <- c(i_true, i)
    }
  }
}
```
2.1 Deleting citation keys that are double
```{r}
citation_keys <- unique(citation_keys)
```

# 3. Use that list to make a references list
```{r}
#easy way without special formatting
bib_file[i_true]
```

